name: EnhancedCrates
version: ${project.version}
main: me.linoxgh.enhancedcrates.EnhancedCrates
api-version: 1.16
authors: [ LinoxGH ]
description: The enhanced solution for your Pay2Win servers!

softdepend: [ Vault ]

commands:
  crates:
    description: "Main command for Crates Enhanced plugin."
    usage: "/crates help"
    permission: crates.main
    permission-message: "ยง4You do not have enough permission to use this command."
    aliases: [ crate ]

permissions:
  crates.*:
    description: "Master permission node for the whole plugin."
    default: op
    children: [ crates.use.*, crates.view.*, crates.admin ]
  crates.use.*:
    description: "Master permission node for using all crate types."
    default: true
  crates.view.*:
    description: "Master permission node for viewing all crate types' rewards."
    default: op

  crates.admin:
    description: "Admin permission node for all editing, creating and deleting."
    default: op
    children: [ crates.create, crates.delete, crates.edit, crates.give, crates.list ]
  crates.create:
    description: "Permission node responsible for creating new crates."
    default: op
    children: [ crates.main ]
  crates.delete:
    description: "Permission node responsible for deleting crates."
    default: op
    children: [ crates.main ]
  crates.edit:
    description: "Permission node responsible for editing crate types."
    default: op
    children: [ crates.main ]
  crates.give:
    description: "Permission node responsible for giving keys."
    default: op
    children: [ crates.main ]
  crates.list:
    description: "Permission node responsible for listing command."
    default: op
    children: [ crates.main ]

  crates.main:
    description: "Main permission node for /crates command."
    default: op
